version: "3.3"

services:

  neo4j: 
    image: neo4j:latest
    container_name: "neo4jdb"
    restart: always 
    ports: 
      - 7474:7474
      - 7687:7687 
    environment: 
      - NEO4J_AUTH=neo4j/12345678

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
      
  mysqldb:
    image: mysql:5.7 
    container_name: "mysqldb" 
    restart: always 
    environment: 
      - MYSQL_ROOT_PASSWORD=12345678 
      - MYSQL_DATABASE=Storage 
    ports: 
      - 3306:3306 
